[project]
name = "jacks-amr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "equinox>=0.12.1",
    "jax>=0.6.0",
    "matplotlib>=3.10.1",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
